FROM node:22.14.0-alpine

ARG ADMIN_PATH=apps/admin


WORKDIR /app/$ADMIN_PATH

COPY ./$ADMIN_PATH/package*.json .

RUN npm ci

COPY $ADMIN_PATH/. . 
   
CMD ["npm", "run", "dev", "--", "--host=0.0.0.0"]
