FROM node:22.14.0-alpine


# Install pnpm globally
RUN corepack enable && corepack prepare pnpm@latest --activate

ARG ADMIN_PATH=apps/admin

WORKDIR /app/$ADMIN_PATH

COPY ./$ADMIN_PATH/package.json .
COPY ./$ADMIN_PATH/pnpm-lock.yaml .

RUN pnpm i

COPY $ADMIN_PATH/. . 
   
CMD ["pnpm", "run", "dev", "--", "--host=0.0.0.0"]
