FROM node:22.14.0-alpine

RUN corepack enable && corepack prepare pnpm@10.32.1 --activate

WORKDIR /app

COPY package*.json .

RUN pnpm i

COPY . . 
   
CMD ["pnpm", "run", "dev", "--", "--host=0.0.0.0"]
