--
-- PostgreSQL database dump
--

\restrict 7vP9kXJBNs8Gp8LmdqjYtpVdQcKXaqksZuUb3BEutyCVVT39pMrcWva7rdiEFZN

-- Dumped from database version 15.14
-- Dumped by pg_dump version 18.0

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: accessibility_features; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.accessibility_features (
    id uuid NOT NULL,
    accessibility_feature character varying(255),
    CONSTRAINT accessibility_features_accessibility_feature_check CHECK (((accessibility_feature)::text = ANY (ARRAY[('RAMPS'::character varying)::text, ('WHEELCHAIRS'::character varying)::text, ('ELEVATORS'::character varying)::text, ('STAIRS'::character varying)::text])))
);


--
-- Name: entity_test; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.entity_test (
    id integer NOT NULL,
    name character varying(255)
);


--
-- Name: entity_test_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.entity_test ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.entity_test_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: facilities; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.facilities (
    id uuid NOT NULL,
    facility character varying(255),
    CONSTRAINT facilities_facility_check CHECK (((facility)::text = ANY (ARRAY[('LIB'::character varying)::text, ('LAB'::character varying)::text, ('GYM'::character varying)::text, ('CAF'::character varying)::text, ('AUD'::character varying)::text, ('PGD'::character varying)::text, ('SWP'::character varying)::text, ('ART'::character varying)::text, ('MUS'::character varying)::text, ('CLAB'::character varying)::text, ('SFLD'::character varying)::text])))
);


--
-- Name: industry_partnerships; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.industry_partnerships (
    id uuid NOT NULL,
    industry_partnership character varying(255)
);


--
-- Name: school_academics; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.school_academics (
    languages_of_instruction integer NOT NULL,
    id uuid NOT NULL,
    accreditation_docs_links character varying(255)
);


--
-- Name: school_accreditations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.school_accreditations (
    school_id uuid NOT NULL,
    accreditation character varying(255),
    CONSTRAINT school_accreditations_accreditation_check CHECK (((accreditation)::text = ANY (ARRAY[('IB'::character varying)::text, ('BSO'::character varying)::text, ('CIS'::character varying)::text, ('Cognia'::character varying)::text, ('AEFE'::character varying)::text, ('NEASC'::character varying)::text, ('WASC'::character varying)::text, ('MSA'::character varying)::text, ('SACS'::character varying)::text, ('ACSI'::character varying)::text])))
);


--
-- Name: school_curriculums; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.school_curriculums (
    school_id uuid NOT NULL,
    curriculum character varying(255),
    CONSTRAINT school_curriculums_curriculum_check CHECK (((curriculum)::text = ANY (ARRAY[('UK'::character varying)::text, ('US'::character varying)::text, ('IB'::character varying)::text, ('CBSE'::character varying)::text, ('IGCSE'::character varying)::text, ('AL'::character varying)::text, ('FR'::character varying)::text, ('DE'::character varying)::text])))
);


--
-- Name: school_facilities; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.school_facilities (
    ai_integration boolean NOT NULL,
    safety_compliance boolean NOT NULL,
    id uuid NOT NULL,
    awards_and_recognitions character varying(255),
    csr_activities character varying(255),
    technology_readiness character varying(255),
    CONSTRAINT school_facilities_technology_readiness_check CHECK (((technology_readiness)::text = ANY (ARRAY[('HIGH'::character varying)::text, ('MEDIUM'::character varying)::text, ('LOW'::character varying)::text])))
);


--
-- Name: school_levels; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.school_levels (
    school_id uuid NOT NULL,
    level character varying(255),
    CONSTRAINT school_levels_level_check CHECK (((level)::text = ANY (ARRAY[('KG'::character varying)::text, ('PRI'::character varying)::text, ('MS'::character varying)::text, ('SEC'::character varying)::text, ('HS'::character varying)::text, ('AL'::character varying)::text, ('IB'::character varying)::text, ('PS'::character varying)::text, ('EL'::character varying)::text, ('MID'::character varying)::text, ('HIG'::character varying)::text, ('UNI'::character varying)::text])))
);


--
-- Name: school_media; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.school_media (
    id uuid NOT NULL,
    bqa_report_link character varying(255),
    brochure_link character varying(255),
    gallery_link character varying(255),
    video_tour_link character varying(255)
);


--
-- Name: school_staff; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.school_staff (
    last_inspection_date date,
    staff_size_estimate integer NOT NULL,
    id uuid NOT NULL,
    leadership_profile_link character varying(255),
    leadership_team character varying(255),
    professional_development character varying(255),
    teacher_qualifications character varying(255)
);


--
-- Name: school_staff_languages; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.school_staff_languages (
    school_staff_id uuid NOT NULL,
    language character varying(255),
    CONSTRAINT school_staff_languages_language_check CHECK (((language)::text = ANY (ARRAY[('en'::character varying)::text, ('es'::character varying)::text, ('ar'::character varying)::text, ('fr'::character varying)::text, ('pt'::character varying)::text, ('de'::character varying)::text, ('it'::character varying)::text, ('ja'::character varying)::text, ('ru'::character varying)::text, ('ko'::character varying)::text, ('zh'::character varying)::text, ('hi'::character varying)::text, ('other'::character varying)::text])))
);


--
-- Name: school_staff_nationalities; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.school_staff_nationalities (
    school_staff_id uuid NOT NULL,
    country character varying(255),
    CONSTRAINT school_staff_nationalities_country_check CHECK (((country)::text = ANY (ARRAY[('BH'::character varying)::text, ('KW'::character varying)::text, ('OM'::character varying)::text, ('QA'::character varying)::text, ('SA'::character varying)::text, ('AE'::character varying)::text])))
);


--
-- Name: schools; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.schools (
    forms_completed boolean NOT NULL,
    last_form_step integer,
    type smallint NOT NULL,
    year_established integer NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    id uuid NOT NULL,
    address character varying(255) NOT NULL,
    city character varying(255) NOT NULL,
    country character varying(255) NOT NULL,
    email character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    phone_number character varying(255) NOT NULL,
    website character varying(255),
    CONSTRAINT schools_country_check CHECK (((country)::text = ANY (ARRAY[('BH'::character varying)::text, ('KW'::character varying)::text, ('OM'::character varying)::text, ('QA'::character varying)::text, ('SA'::character varying)::text, ('AE'::character varying)::text]))),
    CONSTRAINT schools_type_check CHECK (((type >= 0) AND (type <= 3)))
);


--
-- Name: sustainability_practices; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.sustainability_practices (
    id uuid NOT NULL,
    sustainability_practice character varying(255),
    CONSTRAINT sustainability_practices_sustainability_practice_check CHECK (((sustainability_practice)::text = ANY (ARRAY[('SOLAR'::character varying)::text, ('RECYCLING'::character varying)::text, ('WATER_CONSERVATION'::character varying)::text, ('ENERGY_EFFICIENT_LIGHTING'::character varying)::text, ('GREEN_SPACES'::character varying)::text])))
);


--
-- Name: university_destinations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.university_destinations (
    id uuid NOT NULL,
    university_destination character varying(255)
);


--
-- Name: user_schools; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.user_schools (
    id uuid NOT NULL,
    school_id uuid NOT NULL,
    user_id uuid NOT NULL
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users (
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    id uuid NOT NULL,
    email character varying(255) NOT NULL,
    first_name character varying(255) NOT NULL,
    last_name character varying(255) NOT NULL,
    password character varying(255) NOT NULL,
    role character varying(255),
    CONSTRAINT users_role_check CHECK (((role)::text = ANY (ARRAY[('SUPER_ADMIN'::character varying)::text, ('ADMIN'::character varying)::text, ('USER'::character varying)::text])))
);


--
-- Name: entity_test entity_test_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.entity_test
    ADD CONSTRAINT entity_test_pkey PRIMARY KEY (id);


--
-- Name: school_academics school_academics_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.school_academics
    ADD CONSTRAINT school_academics_pkey PRIMARY KEY (id);


--
-- Name: school_facilities school_facilities_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.school_facilities
    ADD CONSTRAINT school_facilities_pkey PRIMARY KEY (id);


--
-- Name: school_media school_media_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.school_media
    ADD CONSTRAINT school_media_pkey PRIMARY KEY (id);


--
-- Name: school_staff school_staff_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.school_staff
    ADD CONSTRAINT school_staff_pkey PRIMARY KEY (id);


--
-- Name: schools schools_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.schools
    ADD CONSTRAINT schools_pkey PRIMARY KEY (id);


--
-- Name: user_schools uklofmfash701d37nykob9sr3ne; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_schools
    ADD CONSTRAINT uklofmfash701d37nykob9sr3ne UNIQUE (user_id, school_id);


--
-- Name: user_schools user_schools_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_schools
    ADD CONSTRAINT user_schools_pkey PRIMARY KEY (id);


--
-- Name: user_schools user_schools_user_id_school_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_schools
    ADD CONSTRAINT user_schools_user_id_school_id_key UNIQUE (user_id, school_id);


--
-- Name: users users_email_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_email_key UNIQUE (email);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: school_accreditations fk1xfet69fsnh3lfo98bdlx560s; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.school_accreditations
    ADD CONSTRAINT fk1xfet69fsnh3lfo98bdlx560s FOREIGN KEY (school_id) REFERENCES public.school_academics(id);


--
-- Name: school_staff_languages fk2kykc1d0n5dbqh403bugn8gj5; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.school_staff_languages
    ADD CONSTRAINT fk2kykc1d0n5dbqh403bugn8gj5 FOREIGN KEY (school_staff_id) REFERENCES public.school_staff(id);


--
-- Name: school_media fk46l53jve44l3ih09flpdrlpl3; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.school_media
    ADD CONSTRAINT fk46l53jve44l3ih09flpdrlpl3 FOREIGN KEY (id) REFERENCES public.schools(id);


--
-- Name: school_levels fk489txseb81u0ox0p4ob8rmi05; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.school_levels
    ADD CONSTRAINT fk489txseb81u0ox0p4ob8rmi05 FOREIGN KEY (school_id) REFERENCES public.school_academics(id);


--
-- Name: facilities fk7x447x42ullrivjxy36gukio7; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.facilities
    ADD CONSTRAINT fk7x447x42ullrivjxy36gukio7 FOREIGN KEY (id) REFERENCES public.school_facilities(id);


--
-- Name: user_schools fk841q00rb2nye05ke1idnpvwql; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_schools
    ADD CONSTRAINT fk841q00rb2nye05ke1idnpvwql FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: industry_partnerships fk9rdysuw6hxia7viwldy4utpwi; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.industry_partnerships
    ADD CONSTRAINT fk9rdysuw6hxia7viwldy4utpwi FOREIGN KEY (id) REFERENCES public.school_facilities(id);


--
-- Name: university_destinations fk9wafxpodmoqhcl9fxlkewrsvs; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.university_destinations
    ADD CONSTRAINT fk9wafxpodmoqhcl9fxlkewrsvs FOREIGN KEY (id) REFERENCES public.school_facilities(id);


--
-- Name: school_staff fkfoh8bib1l0lourm7q9skpleg8; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.school_staff
    ADD CONSTRAINT fkfoh8bib1l0lourm7q9skpleg8 FOREIGN KEY (id) REFERENCES public.schools(id);


--
-- Name: user_schools fkggq5cue5a3b74tgaj8qraayqi; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_schools
    ADD CONSTRAINT fkggq5cue5a3b74tgaj8qraayqi FOREIGN KEY (school_id) REFERENCES public.schools(id);


--
-- Name: school_staff_nationalities fklg7ipapgg8cjnagylrsd37tnr; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.school_staff_nationalities
    ADD CONSTRAINT fklg7ipapgg8cjnagylrsd37tnr FOREIGN KEY (school_staff_id) REFERENCES public.school_staff(id);


--
-- Name: school_academics fko75k4k71bu9iwgt579dafyyo; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.school_academics
    ADD CONSTRAINT fko75k4k71bu9iwgt579dafyyo FOREIGN KEY (id) REFERENCES public.schools(id);


--
-- Name: school_curriculums fko9mvyml9m31eq40st0a3ft1jq; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.school_curriculums
    ADD CONSTRAINT fko9mvyml9m31eq40st0a3ft1jq FOREIGN KEY (school_id) REFERENCES public.school_academics(id);


--
-- Name: sustainability_practices fkojxspwg21520oiyhn07iyvo6n; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sustainability_practices
    ADD CONSTRAINT fkojxspwg21520oiyhn07iyvo6n FOREIGN KEY (id) REFERENCES public.school_facilities(id);


--
-- Name: accessibility_features fksuijvrtddy56a2xvauuumwegp; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.accessibility_features
    ADD CONSTRAINT fksuijvrtddy56a2xvauuumwegp FOREIGN KEY (id) REFERENCES public.school_facilities(id);


--
-- Name: school_facilities fktr6xoo136e0lcr9mcdjh7syj9; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.school_facilities
    ADD CONSTRAINT fktr6xoo136e0lcr9mcdjh7syj9 FOREIGN KEY (id) REFERENCES public.schools(id);


--
-- PostgreSQL database dump complete
--

\unrestrict 7vP9kXJBNs8Gp8LmdqjYtpVdQcKXaqksZuUb3BEutyCVVT39pMrcWva7rdiEFZN

