FROM node:22.14.0-alpine AS admin_build

RUN corepack enable && corepack prepare pnpm@latest --activate

WORKDIR /app

ARG ADMIN_PATH=apps/admin

WORKDIR /app/$ADMIN_PATH

ARG VITE_NODE_ENV
ARG VITE_API_URL

COPY ./$ADMIN_PATH/package.json ./

RUN pnpm install

COPY ./$ADMIN_PATH .

RUN pnpm build



FROM caddy:2.6.2-alpine

COPY --from=admin_build /app/apps/admin/dist /srv/admin

COPY ./proxy/Caddyfile.stage.multi /etc/caddy/Caddyfile