services:
  db:
    image: postgres:15-alpine
    container_name: SchoolRanking-db-dev
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 5444:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
